import About from '@/components/About/About';
import React from 'react'
export const metadata = {
  title: "Portofilio | About page",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <About />
  </>
}

export default page