import ContactPage from '@/components/ContactPage/ContactPage';
import React from 'react'
export const metadata = {
  title: "Portofilio | Contact page",
  description: "Generated by create next app",
};
const Contact = () => {
  return <>
  <ContactPage />
  </>
}

export default Contact